In [1]:
ls

 Volume in drive C has no label.
 Volume Serial Number is D8AF-799C

 Directory of C:\Hamoye Tasks

07/25/2022  02:43 AM    <DIR>          .
07/25/2022  02:43 AM    <DIR>          ..
07/25/2022  02:42 AM    <DIR>          .ipynb_checkpoints
07/23/2022  02:27 PM         8,603,007 FoodBalanceSheets_E_Africa_NOFLAG.csv
07/23/2022  03:18 PM            24,146 Hamoye Stage A Project.ipynb
07/25/2022  02:43 AM               589 Hamoye test(stage A).ipynb
07/25/2022  02:14 AM            13,575 my project.ipynb
07/23/2022  07:09 PM            25,448 Untitled.ipynb
07/25/2022  02:13 AM            13,575 Untitled1.ipynb
               6 File(s)      8,680,340 bytes
               3 Dir(s)  354,120,818,688 bytes free

In [4]:
import pandas as pd
df = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv',encoding="latin-1")

In [5]:
df

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [20]:
df['Area'].nunique()

49

In [24]:
df['Y2015'].describe()

count     59395.000000
mean        135.235966
std        1603.403984
min       -3161.000000
25%           0.000000
50%           0.080000
75%           8.460000
max      181137.000000
Name: Y2015, dtype: float64